server:
  port: 8080

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:default-app}

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY:fakeAccessKey}
        secret-key: ${AWS_SECRET_KEY:fakeSecretKey}

      region:
        static: ${AWS_REGION:sa-east-1}

      stack:
        auto: false

      s3:
        endpoint: ${AWS_ENDPOINT_S3:http://localhost:4566}

      sqs:
        endpoint: ${AWS_ENDPOINT_SQS:http://localhost:4566}

      sns:
        endpoint: ${AWS_ENDPOINT_SNS:http://localhost:4566}

      dynamodb:
        endpoint: ${AWS_ENDPOINT_DYNAMODB:http://localhost:4566}

aws:
  region: ${AWS_REGION:sa-east-1}

  endpoints:
    s3: ${AWS_ENDPOINT_S3:http://localhost:4566}
    sqs: ${AWS_ENDPOINT_SQS:http://localhost:4566}
    sns: ${AWS_ENDPOINT_SNS:http://localhost:4566}
    dynamodb: ${AWS_ENDPOINT_DYNAMODB:http://localhost:4566}